hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment")
    hl.exec_cmd("gnome-keyring-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("brightnessctl -s set 50%")
    hl.exec_cmd("waybar")
    hl.exec_cmd("sh $HOME/.config/hypr/scripts/power_listener.sh")
    hl.exec_cmd("hyprsunset")
end)
